const mongoose = require('mongoose');

// 1. Schema for the questions generated by the AI
const questionSchema = new mongoose.Schema({
  question_id: { 
    type: Number, 
    required: true 
  },
  text: { 
    type: String, 
    required: true 
  },
  target_topics: [{ 
    type: String // The exact subtopics this question evaluates
  }]
}, { _id: false });

// 2. Schema for the user's submitted answers
const answerSchema = new mongoose.Schema({
  question_id: { 
    type: Number, 
    required: true 
  },
  answer_text: { 
    type: String, 
    default: "" 
  }
}, { _id: false });

// 3. Schema for the AI's grading output
const evaluationSchema = new mongoose.Schema({
  topic_name: { 
    type: String // Parent topic name (if available/needed for history)
  },
  subtopic_name: { 
    type: String, 
    required: true // The exact subtopic evaluated
  },
  remarks: { 
    type: String, 
    required: true // Actionable feedback from the AI
  },
  retention: { 
    type: String, 
    enum: ['red', 'yellow', 'green'], 
    required: true // The calibrated score tag
  }
}, { _id: false });

// 4. Main Test Schema
const testSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  subject: {
    type: String,
    required: true,
    trim: true,
    index: true
  },
  status: {
    type: String,
    enum: ['pending', 'graded', 'abandoned'],
    default: 'pending',
    index: true
  },
  questions: {
    type: [questionSchema],
    required: true // Requires questions when the test is created
  },
  answers: {
    type: [answerSchema],
    default: [] // Explicitly defaults to an empty array
  },
  evaluations: {
    type: [evaluationSchema],
    default: [] // Explicitly defaults to an empty array
  }
}, {
  timestamps: true // Automatically handles createdAt and updatedAt
});

// Index to quickly find a user's pending test for a specific subject
testSchema.index({ user: 1, subject: 1, status: 1 });

const Test = mongoose.model('Test', testSchema);

module.exports = Test;